name: libnetconf2 CI
on:
  push:
    branches:
      - master
      - devel
  pull_request:
    branches:
      - master
      - devel

env:
  DEFAULT_OPTIONS: -DENABLE_BUILD_TESTS=ON -DENABLE_DNSSEC=ON
  DEFAULT_PACKAGES: libcmocka-dev zlib1g-dev libssh-dev libssl-dev

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }} # mac-OS does not implement robust mutexes so it is not supported
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "Release, Ubuntu 18.04, gcc",
            os: "ubuntu-18.04",
            build-type: "Release",
            cc: "gcc",
            options: "",
            packager: "sudo apt-get",
            packages: ""
          }
          - {
            name: "Release, Ubuntu 18.04, clang",
            os: "ubuntu-18.04",
            build-type: "Release",
            cc: "clang",
            options: "",
            packager: "sudo apt-get",
            packages: ""
          }
          - {
            name: "Debug, Ubuntu 18.04, gcc",
            os: "ubuntu-18.04",
            build-type: "Debug",
            cc: "gcc",
            options: "",
            packager: "sudo apt-get",
            packages: "valgrind"
          }
          - {
            name: "Debug, Ubuntu 18.04, clang",
            os: "ubuntu-18.04",
            build-type: "Debug",
            cc: "clang",
            options: "",
            packager: "sudo apt-get",
            packages: "valgrind"
          }
          - {
            name: "SSH Only",
            os: "ubuntu-18.04",
            build-type: "Debug",
            cc: "gcc",
            options: "DENABLE_TLS=OFF -DENABLE_SSH=ON",
            packager: "sudo apt-get",
            packages: "valgrind"
          }
          - {
            name: "TLS Only",
            os: "ubuntu-18.04",
            build-type: "Debug",
            cc: "gcc",
            options: "DENABLE_TLS=ON -DENABLE_SSH=OFF",
            packager: "sudo apt-get",
            packages: "valgrind"
          }
          - {
            name: "No SSH nor TLS",
            os: "ubuntu-18.04",
            build-type: "Debug",
            cc: "gcc",
            options: "DENABLE_TLS=OFF -DENABLE_SSH=OFF",
            packager: "sudo apt-get",
            packages: "valgrind"
          }
          - {
            name: "ASAN and UBSAN",
            os: "ubuntu-18.04",
            build-type: "Debug",
            cc: "clang",
            options: "-DCMAKE_C_FLAGS=-fsanitize=address,undefined -DENABLE_VALGRIND_TESTS=OFF",
            packager: "sudo apt-get",
            packages: ""
          }

    steps:
      - uses: actions/checkout@v2

      - name: Uncrustify
        shell: bash
        working-directory: ${{ github.workspace }}
        run: |
          git clone --branch uncrustify-0.71.0 https://github.com/uncrustify/uncrustify
          cd uncrustify
          mkdir build
          cd build
          CC=${{ matrix.config.cc }} cmake ..
          make
          sudo make install
        if: ${{ matrix.config.name == 'Debug, Ubuntu 18.04, gcc' }}

      - name: Dependencies
        shell: bash
        run: |
          sudo add-apt-repository ppa:kedazo/libssh-0.7.x -y
          ${{ matrix.config.packager }} update
          ${{ matrix.config.packager }} install $DEFAULT_PACKAGES ${{ matrix.config.packages }}

          if ${{ github.event_name == 'push' }}
            then GIT_BRANCH=`echo ${{ github.ref }} | cut -d'/' -f 3`
          else
            GIT_BRANCH=${{ github.base_ref }}
          fi

          git clone -b $GIT_BRANCH https://github.com/CESNET/libyang.git
          cd libyang
          mkdir build
          cd build
          CC=${{ matrix.config.cc }} cmake -DCMAKE_BUILD_TYPE=${{ matrix.config.build-type }} -DENABLE_BUILD_TESTS=OFF ..
          make -j2
          sudo make install

          git clone https://github.com/DNSSEC-Tools/DNSSEC-Tools.git dnssec-tools
          cd dnssec-tools/dnssec-tools/validator
          ./configure
          make -j2
          sudo make install


      - name: Configure
        shell: bash
        working-directory: ${{ github.workspace }}
        run: |
          mkdir build
          cd build
          CC=${{ matrix.config.cc }} cmake -DCMAKE_BUILD_TYPE=${{ matrix.config.build-type }} $DEFAULT_OPTIONS ${{ matrix.config.options }} ..

      - name: Build
        shell: bash
        working-directory: ${{ github.workspace }}/build
        run: make

      - name: Test
        shell: bash
        working-directory: ${{ github.workspace }}/build
        run: ctest --output-on-failure

  abi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Dependencies
        shell: bash
        run: |
          sudo add-apt-repository ppa:kedazo/libssh-0.7.x -y
          sudo apt-get update
          sudo apt-get install $DEFAULT_PACKAGES abi-dumper abi-compliance-checker
          sudo snap install core universal-ctags

          if ${{ github.event_name == 'push' }}
            then GIT_BRANCH=`echo ${{ github.ref }} | cut -d'/' -f 3`
          else
            GIT_BRANCH=${{ github.base_ref }}
          fi

          git clone -b $GIT_BRANCH https://github.com/CESNET/libyang.git
          cd libyang
          mkdir build
          cd build
          CC=gcc cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_BUILD_TESTS=OFF ..
          make -j2
          sudo make install

          git clone https://github.com/DNSSEC-Tools/DNSSEC-Tools.git dnssec-tools
          cd dnssec-tools/dnssec-tools/validator
          ./configure
          make -j2
          sudo make install

      - name: Configure
        shell: bash
        working-directory: ${{ github.workspace }}
        run: |
          mkdir build
          cd build
          CC=gcc cmake -DCMAKE_BUILD_TYPE=ABICheck ..

      - name: Build
        shell: bash
        working-directory: ${{ github.workspace }}/build
        run: LC_ALL=C.UTF-8 PATH=/snap/bin:$PATH make abi-check

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Dependencies
        shell: bash
        run: |
          sudo add-apt-repository ppa:kedazo/libssh-0.7.x -y
          sudo apt-get update
          sudo apt-get install $DEFAULT_PACKAGES lcov

          if ${{ github.event_name == 'push' }}
            then GIT_BRANCH=`echo ${{ github.ref }} | cut -d'/' -f 3`
          else
            GIT_BRANCH=${{ github.base_ref }}
          fi

          git clone -b $GIT_BRANCH https://github.com/CESNET/libyang.git
          cd libyang
          mkdir build
          cd build
          CC=gcc cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_BUILD_TESTS=OFF ..
          make -j2
          sudo make install

      - name: Configure
        shell: bash
        working-directory: ${{ github.workspace }}
        run: |
          mkdir build
          cd build
          CC=gcc cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_COVERAGE=ON ..

      - name: Build
        shell: bash
        working-directory: ${{ github.workspace }}/build
        run: make

      - name: Test
        shell: bash
        working-directory: ${{ github.workspace }}/build
        run: ctest --output-on-failure

      - name: Upload to Codecov.io
        shell: bash
        working-directory: ${{ github.workspace }}/build
        run: bash <(curl -s https://codecov.io/bash)
